#!/bin/bash

SELF_DIR="$(realpath "$(dirname "${BASH_SOURCE}")")"
TAG="isa"

# build image if it doesn't exist
if [[ $(docker images -q "$TAG" 2> /dev/null) == '' ]]; then
  "${SELF_DIR}/build"
fi

NET_ARG=""
if [[ "$1" == "--net=host" || "$1" == "--network=host" ]]; then
  NET_ARG="--net=host"
  shift
fi

docker run --platform linux/x86_64 -it --rm ${NET_ARG} -v "${SELF_DIR}":/app $TAG "${@:-bash}"
